name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  google_sign_in: ^5.0.2
  meta: ^1.3.0
  firebase_dynamic_links: ^2.0.1
  formz: ^0.4.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.5
